spring:
  h2:
    console:
      enabled: true
#      path: /h2
  datasource:
#    url: jdbc:h2:~/coindesk
    url: jdbc:h2:mem:coindesk
    username: test
    password: 123
    driverClassName: org.h2.Driver
  jpa: 
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties: 
      hibernate: 
        jdbc:
          batch-size: 10

server:     
  port: 8080